local mark = require("harpoon.mark")
local ui = require("harpoon.ui")
local term = require("harpoon.term")
vim.keymap.set("n", "<leader>ma", mark.add_file)
vim.keymap.set("n", "<leader>mm", ui.toggle_quick_menu)
