local mark = require("harpoon.mark")
local ui = require("harpoon.ui")
vim.keymap.set("n", "<leader>ma", mark.add_file)
vim.keymap.set("n", "<leader>mm", ui.toggle_quick_menu)
--require('telescope').load_extension('harpoon')
--vim.keymap.set('n', '<leader>mm', '<cmd>Telescope harpoon marks<cr>')
